name: tournament_app
description: "Tournament Management Flutter App - Quản Lý Giải Đấu"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # HTTP & API
  http: ^1.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  cached_network_image: ^3.3.0
  flutter_html: ^3.0.0-beta.2
  fl_chart: ^0.69.0
  
  # Utilities
  intl: ^0.18.1
  json_annotation: ^4.8.1
  timeago: ^3.7.0
  
  # SignalR for real-time updates
  signalr_netcore: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Launcher Icons
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/LOGO.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/LOGO.jpg"
